from enum import Enum


class CountryEnum(str, Enum):
    AL = "AL"
    AT = "AT"
    BA = "BA"
    BE = "BE"
    BG = "BG"
    CH = "CH"
    CY = "CY"
    CZ = "CZ"
    DE = "DE"
    DK = "DK"
    EE = "EE"
    ES = "ES"
    EU = "EU"
    FI = "FI"
    FR = "FR"
    GB = "GB"
    GE = "GE"
    GR = "GR"
    HR = "HR"
    HU = "HU"
    IE = "IE"
    IS = "IS"
    IT = "IT"
    LT = "LT"
    LU = "LU"
    LV = "LV"
    MC = "MC"
    MK = "MK"
    MT = "MT"
    NL = "NL"
    NO = "NO"
    PL = "PL"
    PT = "PT"
    RO = "RO"
    RS = "RS"
    SE = "SE"
    SI = "SI"
    SK = "SK"
    UA = "UA"

    def __str__(self) -> str:
        return str(self.value)
