from enum import Enum


class CustomersListFieldItem(str, Enum):
    ABBREVIATION = "abbreviation"
    ACCESS_SUBNETS = "access_subnets"
    ACCOUNTING_START_DATE = "accounting_start_date"
    ADDRESS = "address"
    AGREEMENT_NUMBER = "agreement_number"
    ARCHIVED = "archived"
    BACKEND_ID = "backend_id"
    BANK_ACCOUNT = "bank_account"
    BANK_NAME = "bank_name"
    BILLING_PRICE_ESTIMATE = "billing_price_estimate"
    BLOCKED = "blocked"
    CALL_MANAGING_ORGANIZATION_UUID = "call_managing_organization_uuid"
    CONTACT_DETAILS = "contact_details"
    COUNTRY = "country"
    COUNTRY_NAME = "country_name"
    CREATED = "created"
    CUSTOMER_CREDIT = "customer_credit"
    CUSTOMER_UNALLOCATED_CREDIT = "customer_unallocated_credit"
    DEFAULT_TAX_PERCENT = "default_tax_percent"
    DISPLAY_NAME = "display_name"
    DOMAIN = "domain"
    EMAIL = "email"
    HOMEPAGE = "homepage"
    IMAGE = "image"
    IS_SERVICE_PROVIDER = "is_service_provider"
    LATITUDE = "latitude"
    LONGITUDE = "longitude"
    MAX_SERVICE_ACCOUNTS = "max_service_accounts"
    NAME = "name"
    NATIVE_NAME = "native_name"
    ORGANIZATION_GROUPS = "organization_groups"
    PAYMENT_PROFILES = "payment_profiles"
    PHONE_NUMBER = "phone_number"
    POSTAL = "postal"
    PROJECTS_COUNT = "projects_count"
    REGISTRATION_CODE = "registration_code"
    SERVICE_PROVIDER = "service_provider"
    SERVICE_PROVIDER_UUID = "service_provider_uuid"
    SLUG = "slug"
    SPONSOR_NUMBER = "sponsor_number"
    URL = "url"
    USERS_COUNT = "users_count"
    UUID = "uuid"
    VAT_CODE = "vat_code"

    def __str__(self) -> str:
        return str(self.value)
