from enum import Enum


class MarketplaceOfferingUsersRetrieveFieldItem(str, Enum):
    CONSENT_DATA = "consent_data"
    CREATED = "created"
    CUSTOMER_NAME = "customer_name"
    CUSTOMER_UUID = "customer_uuid"
    HAS_COMPLIANCE_CHECKLIST = "has_compliance_checklist"
    HAS_CONSENT = "has_consent"
    IS_RESTRICTED = "is_restricted"
    MODIFIED = "modified"
    OFFERING = "offering"
    OFFERING_NAME = "offering_name"
    OFFERING_UUID = "offering_uuid"
    REQUIRES_RECONSENT = "requires_reconsent"
    SERVICE_PROVIDER_COMMENT = "service_provider_comment"
    SERVICE_PROVIDER_COMMENT_URL = "service_provider_comment_url"
    STATE = "state"
    URL = "url"
    USER = "user"
    USERNAME = "username"
    USER_AFFILIATIONS = "user_affiliations"
    USER_BIRTH_DATE = "user_birth_date"
    USER_CIVIL_NUMBER = "user_civil_number"
    USER_COUNTRY_OF_RESIDENCE = "user_country_of_residence"
    USER_EDUPERSON_ASSURANCE = "user_eduperson_assurance"
    USER_EMAIL = "user_email"
    USER_FULL_NAME = "user_full_name"
    USER_GENDER = "user_gender"
    USER_IDENTITY_SOURCE = "user_identity_source"
    USER_JOB_TITLE = "user_job_title"
    USER_NATIONALITIES = "user_nationalities"
    USER_NATIONALITY = "user_nationality"
    USER_ORGANIZATION = "user_organization"
    USER_ORGANIZATION_COUNTRY = "user_organization_country"
    USER_ORGANIZATION_TYPE = "user_organization_type"
    USER_PERSONAL_TITLE = "user_personal_title"
    USER_PHONE_NUMBER = "user_phone_number"
    USER_PLACE_OF_BIRTH = "user_place_of_birth"
    USER_USERNAME = "user_username"
    USER_UUID = "user_uuid"
    UUID = "uuid"

    def __str__(self) -> str:
        return str(self.value)
