from enum import Enum


class OpenportalUnmanagedProjectsRetrieveFieldItem(str, Enum):
    BACKEND_ID = "backend_id"
    BILLING_PRICE_ESTIMATE = "billing_price_estimate"
    CREATED = "created"
    CUSTOMER = "customer"
    CUSTOMER_ABBREVIATION = "customer_abbreviation"
    CUSTOMER_DISPLAY_BILLING_INFO_IN_PROJECTS = "customer_display_billing_info_in_projects"
    CUSTOMER_NAME = "customer_name"
    CUSTOMER_NATIVE_NAME = "customer_native_name"
    CUSTOMER_SLUG = "customer_slug"
    CUSTOMER_UUID = "customer_uuid"
    DESCRIPTION = "description"
    END_DATE = "end_date"
    END_DATE_REQUESTED_BY = "end_date_requested_by"
    GRACE_PERIOD_DAYS = "grace_period_days"
    IMAGE = "image"
    IS_INDUSTRY = "is_industry"
    IS_REMOVED = "is_removed"
    KIND = "kind"
    MARKETPLACE_RESOURCE_COUNT = "marketplace_resource_count"
    MAX_SERVICE_ACCOUNTS = "max_service_accounts"
    NAME = "name"
    OECD_FOS_2007_CODE = "oecd_fos_2007_code"
    OECD_FOS_2007_LABEL = "oecd_fos_2007_label"
    PROJECT_CREDIT = "project_credit"
    RESOURCES_COUNT = "resources_count"
    SLUG = "slug"
    STAFF_NOTES = "staff_notes"
    START_DATE = "start_date"
    TERMINATION_METADATA = "termination_metadata"
    TYPE = "type"
    TYPE_NAME = "type_name"
    TYPE_UUID = "type_uuid"
    URL = "url"
    USER_AFFILIATIONS = "user_affiliations"
    USER_EMAIL_PATTERNS = "user_email_patterns"
    USER_IDENTITY_SOURCES = "user_identity_sources"
    UUID = "uuid"

    def __str__(self) -> str:
        return str(self.value)
