from enum import Enum


class PermissionMetadataResponseRolesAdditionalProperty(str, Enum):
    CALL_MANAGER = "CALL.MANAGER"
    CALL_REVIEWER = "CALL.REVIEWER"
    CUSTOMER_MANAGER = "CUSTOMER.MANAGER"
    CUSTOMER_OWNER = "CUSTOMER.OWNER"
    CUSTOMER_SUPPORT = "CUSTOMER.SUPPORT"
    OFFERING_MANAGER = "OFFERING.MANAGER"
    PROJECT_ADMIN = "PROJECT.ADMIN"
    PROJECT_MANAGER = "PROJECT.MANAGER"
    PROJECT_MEMBER = "PROJECT.MEMBER"
    PROPOSAL_MANAGER = "PROPOSAL.MANAGER"
    PROPOSAL_MEMBER = "PROPOSAL.MEMBER"

    def __str__(self) -> str:
        return str(self.value)
