from enum import Enum


class UsersRetrieveFieldItem(str, Enum):
    AFFILIATIONS = "affiliations"
    AGREEMENT_DATE = "agreement_date"
    AGREE_WITH_POLICY = "agree_with_policy"
    BIRTH_DATE = "birth_date"
    CIVIL_NUMBER = "civil_number"
    COUNTRY_OF_RESIDENCE = "country_of_residence"
    DATE_JOINED = "date_joined"
    DESCRIPTION = "description"
    EDUPERSON_ASSURANCE = "eduperson_assurance"
    EMAIL = "email"
    FIRST_NAME = "first_name"
    FULL_NAME = "full_name"
    GENDER = "gender"
    HAS_ACTIVE_SESSION = "has_active_session"
    IDENTITY_PROVIDER_FIELDS = "identity_provider_fields"
    IDENTITY_PROVIDER_LABEL = "identity_provider_label"
    IDENTITY_PROVIDER_MANAGEMENT_URL = "identity_provider_management_url"
    IDENTITY_PROVIDER_NAME = "identity_provider_name"
    IDENTITY_SOURCE = "identity_source"
    IMAGE = "image"
    IP_ADDRESS = "ip_address"
    IS_ACTIVE = "is_active"
    IS_STAFF = "is_staff"
    IS_SUPPORT = "is_support"
    JOB_TITLE = "job_title"
    LAST_NAME = "last_name"
    NATIONALITIES = "nationalities"
    NATIONALITY = "nationality"
    NATIVE_NAME = "native_name"
    NOTIFICATIONS_ENABLED = "notifications_enabled"
    ORGANIZATION = "organization"
    ORGANIZATION_COUNTRY = "organization_country"
    ORGANIZATION_REGISTRY_CODE = "organization_registry_code"
    ORGANIZATION_TYPE = "organization_type"
    PERMISSIONS = "permissions"
    PERSONAL_TITLE = "personal_title"
    PHONE_NUMBER = "phone_number"
    PLACE_OF_BIRTH = "place_of_birth"
    PREFERRED_LANGUAGE = "preferred_language"
    REGISTRATION_METHOD = "registration_method"
    REQUESTED_EMAIL = "requested_email"
    SLUG = "slug"
    TOKEN = "token"
    TOKEN_EXPIRES_AT = "token_expires_at"
    TOKEN_LIFETIME = "token_lifetime"
    URL = "url"
    USERNAME = "username"
    UUID = "uuid"

    def __str__(self) -> str:
        return str(self.value)
